name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - name: Run Python script
        run: python hello.py

      - name: Logging step
        # run: echo "::debug::Set the Octocat variable"
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "Another line"
            echo "::endgroup::"

      - name: Set the value
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: Use the value
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

          
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: .
      - run: echo "Artifact uploaded" >> $GITHUB_STEP_SUMMARY
