name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - name: Run Python script
        run: python hello.py

      - name: Logging step
        id: my-step
        run: |
          summary="The testing has completed"
          echo "::set-output name=summary::$summary"
          
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: .
      - run: echo "Artifact uploaded" >> $GITHUB_STEP_SUMMARY
